# Generated by Django 4.2.7 on 2023-11-27 21:12

import comm.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="cover",
            field=models.ImageField(
                null=True, upload_to=comm.models.BlogPost.get_cover_upload_path
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(null=True, upload_to="avatars/"),
        ),
    ]
