# Generated by Django 4.2.7 on 2023-12-14 20:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comm", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blogpost",
            old_name="author",
            new_name="user",
        ),
    ]
