# Generated by Django 4.2.7 on 2023-11-27 21:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comm", "0003_alter_tag_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="tags",
        ),
    ]
