# Generated by Django 4.2.7 on 2023-12-02 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("comm", "0004_remove_blogpost_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name="blogpost",
            name="topic",
            field=models.ForeignKey(
                default="Other",
                on_delete=django.db.models.deletion.CASCADE,
                to="comm.topic",
            ),
        ),
    ]
