# Generated by Django 4.2.7 on 2023-12-02 17:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comm", "0006_alter_blogpost_topic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="topic",
        ),
    ]
