# Generated by Django 4.2.7 on 2023-12-02 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("comm", "0009_remove_blogpost_topic"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="topic",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topics",
                to="comm.topic",
            ),
        ),
    ]
